version: 2.1

orbs:
  codecov: codecov/codecov@1
  snyk: snyk/snyk@0.0.10

executors:
  gradle_docker:
    docker:
      - image: cimg/openjdk:11.0
  gradle_machine:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      JVM_OPTS: -Xmx2g
  helm:
    docker:
      - image: hypertrace/helm-gcs-packager:0.1.1
commands:
  gradle:
    description: 'Run the provided gradle command'
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info --max-workers=2 -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.console=plain --continue
          when: << parameters.when >>
  setup_build_environment:
    description: 'Generates cache key from a hash of all gradle files'
    steps:
      - checkout
      - run:
          name: Generate cache key
          command: find . -type f -name "*.gradle*" -exec shasum {} + | sort > /tmp/checksum.txt && cat /tmp/checksum.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  populate_and_save_cache:
    description: 'Downloads all gradle dependencies and uploads cache for later use'
    steps:
      - gradle:
          args: downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
  save_test_results:
    description: "Save test results"
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  machine_install_java11:
    description: "Install java11 on machine executor"
    steps:
      - run:
          name: Install open jdk11
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-11-jdk
            sudo sh -c 'for bin in /usr/lib/jvm/java-11-openjdk-amd64/bin/*; do update-alternatives --install /usr/bin/$(basename $bin) $(basename $bin) $bin 100; done'
            sudo sh -c 'for bin in /usr/lib/jvm/java-11-openjdk-amd64/bin/*; do update-alternatives --set $(basename $bin) $bin; done'

jobs:
  build:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - setup_remote_docker
      - populate_and_save_cache
      - gradle:
          args: build dockerBuildImages
      - gradle:
          args: jacocoTestReport
      - codecov/upload:
          flags: unit
      - save_test_results
  integration-test:
    executor: gradle_machine
    steps:
      - machine_install_java11
      - setup_build_environment
      - populate_and_save_cache
      - gradle:
          args: jacocoIntegrationTestReport
      - codecov/upload:
          flags: integration
      - save_test_results
  publish:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - setup_remote_docker
      - gradle:
          args: :tag -Prelease
      - gradle:
          args: publish dockerPushImages
      - add_ssh_keys:
          fingerprints:
            - 'e3:b6:18:f1:68:bd:71:fe:9a:8b:08:aa:94:f5:1a:31'
      - run: git push origin $(./gradlew -q :printVersion)
  validate-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Helm Charts Lint and Template Render
          command: |
            helm dependency update ./helm/
            helm lint --strict ./helm/
            helm template ./helm/
  snyk-scan:
    executor:
      name: gradle_docker
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 # Snyk doesn't handle parallelism well
    steps:
      - setup_build_environment
      - snyk/scan:
          additional-arguments: --all-sub-projects --policy-path=.snyk
  package-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Package and Publish Helm Charts
          command: |
            CHART_VERSION=$(git describe --abbrev=0)
            CHART_NAME=$(awk '/^name:/ {print $2}' ./helm/Chart.yaml)
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/helm-gcs-key.json
            echo ${HELM_GCS_CREDENTIALS} > ${GOOGLE_APPLICATION_CREDENTIALS}
            helm dependency update ./helm/
            helm repo add helm-gcs ${HELM_GCS_REPOSITORY}
            helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} ./helm/
            helm gcs push ${CHART_NAME}-${CHART_VERSION}.tgz helm-gcs --public --retry

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - integration-test
      - validate-charts
      - snyk-scan:
          context: hypertrace-vulnerability-scanning
      - publish:
          context: hypertrace-publishing
          requires:
            - build
            - integration-test
            - validate-charts
            - snyk-scan
          filters:
            branches:
              only:
                - main
      - package-charts:
          context: hypertrace-publishing
          requires:
            - publish
          filters:
            branches:
              only:
                - main
