# result of merging config1.yaml and config2.yaml
invoice: 34843
date   : "2002-02-22"
bill-to:
  given  : C2
  family : D2
  address:
    lines: |
      222 Walkman Dr.
      Suite #292
    city    : Royal Oak
    state   : MI
    postal  : 48046
ship-to:
  given  : C1
  family : D1
  address:
    lines: |
      111 Walkman Dr.
      Suite #111
    city    : Royal Oak
    postal  : 48046
product:
  - sku         : BL222D
    quantity    : 4
    description : Basketball
    price       : 450.00
  - sku         : BL333H
    quantity    : 1
    description : Super Hoop
    price       : 2392.00
tax  : 251.42
total: 4443.52
comments:
  Late afternoon is best.
  Backup contact is Nancy
  Billsmer @ 338-4338.